openapi: 3.0.3
info:
  title: Supabase Contacts API
  description: API for retrieving paginated contact data from Supabase database
  version: 1.0.0
  contact:
    name: LoanArk CRM Sync Team

servers:
  - url: /.netlify/functions/hubspot-contacts-sync
    description: Netlify Function endpoint

paths:
  /:
    get:
      summary: Get paginated contacts from Supabase
      description: Retrieve contacts synchronized from HubSpot to Supabase with server-side pagination
      operationId: getSupabaseContacts
      tags:
        - contacts
        - pagination
      parameters:
        - name: limit
          in: query
          description: Number of contacts to return per page (1-100)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
        - name: offset
          in: query
          description: Number of contacts to skip (0-based)
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: properties
          in: query
          description: Comma-separated list of contact properties to include
          required: false
          schema:
            type: string
            default: "hs_object_id,email,email_verification_status,firstname,lastname,phone,mobilephone,client_type_vip_status,client_type_prospects,address,city,zip,createdate,lastmodifieddate"
      responses:
        '200':
          description: Successful response with paginated contacts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListResponse'
              example:
                contacts:
                  - hs_object_id: "12345"
                    email: "john.doe@example.com"
                    firstname: "John"
                    lastname: "Doe"
                    createdate: "2023-01-15T10:30:00Z"
                    lastmodifieddate: "2023-06-20T14:45:00Z"
                total: 1250
                hasMore: true
                pagination:
                  pageIndex: 0
                  pageSize: 25
                  totalPages: 50
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Authentication required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Contact:
      type: object
      required:
        - hs_object_id
      properties:
        hs_object_id:
          type: string
          description: HubSpot contact ID
          example: "12345"
        email:
          type: string
          format: email
          description: Contact email address
          example: "john.doe@example.com"
        email_verification_status:
          type: string
          enum: ["verified", "unverified", "unknown"]
          description: Email verification status
          example: "verified"
        firstname:
          type: string
          description: Contact first name
          example: "John"
        lastname:
          type: string
          description: Contact last name
          example: "Doe"
        phone:
          type: string
          description: Primary phone number
          example: "+1-555-0123"
        mobilephone:
          type: string
          description: Mobile phone number
          example: "+1-555-0124"
        client_type_vip_status:
          type: string
          description: VIP client status
          example: "true"
        client_type_prospects:
          type: string
          description: Prospect client type
          example: "hot"
        address:
          type: string
          description: Street address
          example: "123 Main St"
        city:
          type: string
          description: City
          example: "San Francisco"
        zip:
          type: string
          description: Postal code
          example: "94105"
        createdate:
          type: string
          format: date-time
          description: Contact creation date
          example: "2023-01-15T10:30:00Z"
        lastmodifieddate:
          type: string
          format: date-time
          description: Last modification date
          example: "2023-06-20T14:45:00Z"

    ContactListResponse:
      type: object
      required:
        - contacts
        - total
        - hasMore
      properties:
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
          description: Array of contact records
        total:
          type: integer
          minimum: 0
          description: Total number of contacts available
          example: 1250
        hasMore:
          type: boolean
          description: Whether more contacts are available beyond current page
          example: true
        pagination:
          type: object
          description: Optional pagination metadata
          properties:
            pageIndex:
              type: integer
              minimum: 0
              description: Current page index (0-based)
              example: 0
            pageSize:
              type: integer
              minimum: 1
              maximum: 100
              description: Number of records per page
              example: 25
            totalPages:
              type: integer
              minimum: 0
              description: Total number of pages available
              example: 50

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Database query failed"
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
          description: Empty array on error
        total:
          type: integer
          example: 0
        hasMore:
          type: boolean
          example: false

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Supabase service role key or anon key for authentication

security:
  - ApiKeyAuth: []