openapi: 3.0.3
info:
  title: HubSpot Contacts API
  description: API contracts for HubSpot database and live contacts pages
  version: 1.0.0
  contact:
    name: LoanArk CRM Sync Team

servers:
  - url: https://loanark-crm-sync.netlify.app/.netlify/functions
    description: Production server

paths:
  /hubspot-contacts-sync:
    get:
      summary: Get synced HubSpot contacts from database
      description: Retrieve contacts that have been synchronized to the local database
      operationId: getSyncedContacts
      parameters:
        - name: limit
          in: query
          description: Maximum number of contacts to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          description: Number of contacts to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListResponse'
        '401':
          description: Unauthorized - Invalid or missing authentication
        '500':
          description: Internal server error

  /hubspot-contacts-live:
    get:
      summary: Get live HubSpot contacts from API
      description: Retrieve contacts directly from HubSpot CRM API
      operationId: getLiveContacts
      parameters:
        - name: limit
          in: query
          description: Maximum number of contacts to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          description: Number of contacts to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: properties
          in: query
          description: Comma-separated list of properties to retrieve
          required: false
          schema:
            type: string
            default: "hs_object_id,email,email_verification_status,firstname,lastname,phone,mobilephone,client_type_vip_status,client_type_prospects,address,city,zip,createdate,lastmodifieddate"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactListResponse'
        '401':
          description: Unauthorized - Invalid HubSpot authentication
        '429':
          description: Too many requests - HubSpot API rate limit exceeded
        '500':
          description: Internal server error

components:
  schemas:
    HubSpotContact:
      type: object
      required:
        - hs_object_id
        - email
        - createdate
        - lastmodifieddate
      properties:
        hs_object_id:
          type: string
          description: Unique HubSpot object identifier
        email:
          type: string
          format: email
          description: Primary email address
        email_verification_status:
          type: string
          enum: [verified, unverified, unknown]
          description: Email verification status
        firstname:
          type: string
          maxLength: 100
          description: Contact's first name
        lastname:
          type: string
          maxLength: 100
          description: Contact's last name
        phone:
          type: string
          description: Primary phone number
        mobilephone:
          type: string
          description: Mobile phone number
        client_type_vip_status:
          type: string
          description: VIP client classification
        client_type_prospects:
          type: string
          description: Prospect classification
        address:
          type: string
          maxLength: 255
          description: Street address
        city:
          type: string
          maxLength: 100
          description: City
        zip:
          type: string
          description: Postal/ZIP code
        createdate:
          type: string
          format: date-time
          description: Creation timestamp
        lastmodifieddate:
          type: string
          format: date-time
          description: Last modification timestamp

    ContactListResponse:
      type: object
      required:
        - contacts
        - total
        - hasMore
      properties:
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/HubSpotContact'
        total:
          type: integer
          minimum: 0
          description: Total number of contacts available
        hasMore:
          type: boolean
          description: Whether there are more contacts available

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT