openapi: 3.0.3
info:
  title: LoanArk CRM Sync API
  version: 1.0.0
  description: API for synchronizing HubSpot CRM data with LoanArk system

servers:
  - url: https://api.loanark.com/v1
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

security:
  - bearerAuth: []

paths:
  /contacts:
    get:
      summary: List contacts
      description: Retrieve a paginated list of contacts with optional filtering
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 25
          description: Number of contacts per page
        - name: search
          in: query
          schema:
            type: string
            minLength: 1
          description: Search term for contact name or email
        - name: sync_status
          in: query
          schema:
            type: string
            enum: [synced, pending, error]
          description: Filter by sync status
        - name: sort_by
          in: query
          schema:
            type: string
            enum: [name, email, created_at, updated_at, last_sync]
            default: updated_at
          description: Field to sort by
        - name: sort_order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: Sort order
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Contact'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  meta:
                    $ref: '#/components/schemas/Meta'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /contacts/sync:
    post:
      summary: Trigger manual sync
      description: Manually trigger synchronization of contacts from HubSpot
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                full_sync:
                  type: boolean
                  default: false
                  description: Perform full sync instead of incremental
                contact_ids:
                  type: array
                  items:
                    type: string
                  description: Specific contact IDs to sync (optional)
      responses:
        '202':
          description: Sync initiated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  session_id:
                    type: string
                    description: Unique sync session identifier
                  message:
                    type: string
                    example: 'Sync initiated successfully'
                  estimated_duration:
                    type: string
                    example: '5-10 minutes'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Sync already in progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Sync already in progress'
                  current_session_id:
                    type: string
        '500':
          $ref: '#/components/responses/InternalServerError'

  /sync/status:
    get:
      summary: Get sync status
      description: Retrieve the current synchronization status and recent history
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_session:
                    $ref: '#/components/schemas/SyncSession'
                  recent_sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/SyncSession'
                    maxItems: 10
                  statistics:
                    $ref: '#/components/schemas/SyncStatistics'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /connections/hubspot:
    get:
      summary: Check HubSpot connection
      description: Verify the current HubSpot connection status
      responses:
        '200':
          description: Connection status retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  connected:
                    type: boolean
                    description: Whether HubSpot is connected
                  expires_at:
                    type: string
                    format: date-time
                    description: Token expiration time
                  last_tested:
                    type: string
                    format: date-time
                    description: Last connection test time
                  account_info:
                    type: object
                    properties:
                      portal_id:
                        type: string
                        description: HubSpot portal ID
                      account_name:
                        type: string
                        description: HubSpot account name
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Establish HubSpot connection
      description: Initiate OAuth flow to connect to HubSpot
      responses:
        '200':
          description: Connection established
          content:
            application/json:
              schema:
                type: object
                properties:
                  connected:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'HubSpot connection established successfully'
        '302':
          description: Redirect to HubSpot OAuth
          headers:
            Location:
              schema:
                type: string
              description: HubSpot OAuth URL
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Contact:
      type: object
      required:
        - id
        - hubspot_id
        - data
        - last_sync
        - sync_status
      properties:
        id:
          type: string
          format: uuid
          description: Internal contact ID
        hubspot_id:
          type: string
          description: HubSpot contact ID
        data:
          type: object
          description: Complete contact data from HubSpot
          properties:
            properties:
              type: object
              properties:
                firstname:
                  type: string
                  description: Contact first name
                lastname:
                  type: string
                  description: Contact last name
                email:
                  type: string
                  format: email
                  description: Contact email address
                phone:
                  type: string
                  description: Contact phone number
                company:
                  type: string
                  description: Contact company
                createdate:
                  type: string
                  format: date-time
                  description: Contact creation date
                lastmodifieddate:
                  type: string
                  format: date-time
                  description: Last modification date
        last_sync:
          type: string
          format: date-time
          description: Last synchronization timestamp
        sync_status:
          type: string
          enum: [synced, pending, error]
          description: Current sync status
        created_at:
          type: string
          format: date-time
          description: Record creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp

    Pagination:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
          description: Current page number
        limit:
          type: integer
          minimum: 1
          maximum: 100
          description: Items per page
        total:
          type: integer
          minimum: 0
          description: Total number of items
        total_pages:
          type: integer
          minimum: 1
          description: Total number of pages

    Meta:
      type: object
      properties:
        request_id:
          type: string
          description: Unique request identifier
        timestamp:
          type: string
          format: date-time
          description: Response timestamp
        version:
          type: string
          description: API version

    SyncSession:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Session ID
        session_id:
          type: string
          description: Human-readable session identifier
        start_time:
          type: string
          format: date-time
          description: Sync start time
        end_time:
          type: string
          format: date-time
          description: Sync end time
        status:
          type: string
          enum: [pending, running, completed, failed]
          description: Session status
        records_count:
          type: integer
          minimum: 0
          description: Number of records processed
        error_count:
          type: integer
          minimum: 0
          description: Number of errors encountered
        duration:
          type: string
          description: Session duration (calculated)

    SyncStatistics:
      type: object
      properties:
        total_contacts:
          type: integer
          minimum: 0
          description: Total contacts in system
        synced_contacts:
          type: integer
          minimum: 0
          description: Successfully synced contacts
        pending_contacts:
          type: integer
          minimum: 0
          description: Contacts pending sync
        error_contacts:
          type: integer
          minimum: 0
          description: Contacts with sync errors
        last_sync:
          type: string
          format: date-time
          description: Last successful sync time
        average_sync_duration:
          type: string
          description: Average sync duration

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Invalid request parameters'
              details:
                type: object
                description: Validation error details

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Authentication required'
              code:
                type: string
                example: 'UNAUTHORIZED'

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: 'Internal server error'
              request_id:
                type: string
                description: Request ID for debugging

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
